# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField()),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=200)),
                ('fechaInicio', models.DateTimeField(default=datetime.date.today)),
                ('entidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.Entidad')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='entidadID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.Entidad'),
        ),
    ]
