# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechaInicio',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='fechaInicio'),
        ),
    ]
