# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_auto_20160424_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
    ]
