# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0004_auto_20160424_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechaInicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
