# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0005_auto_20160424_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
